# -*- coding: utf-8 -*-
"""
Created on Tue Aug 16 23:05:49 2022

@author: Anderson Almeida
"""

import streamlit as st
from PIL import Image


st.set_page_config(page_title="Methodology",layout='centered', page_icon='🧩')
st.sidebar.image("images/logo.png", use_column_width=True)

st.title('Methodology')

url = 'https://discuss.streamlit.io/t/how-to-create-a-dynamic-clicable-hyperlink-or-button-in-streamlit/12959'

st.write('''
         
In this study, we propose a new method to compute the masses of open clusters, here considered as the mass of member stars, which were determined through membership methods. The method is based on the determination of individual cluster member star masses using precise age, distance, metallicity, and extinction parameters obtained from \emph{Gaia} data. To estimate the individual member star masses, synthetic clusters are generated with full control of fundamental parameters. Finally, a Monte Carlo method is used to obtain the final individual masses, as well as their uncertainties, by comparing the observed and generated synthetic clusters. From the individual masses of the stars and an estimation of the unseen mass in low mass stars as well as remnants of evolved stars, the masses of the clusters are obtained. We validate the method by using a set of simulated observations based on synthetic clusters generated from predefined isochrones of given age, distance, extinction and metallicitiy as well as binary fraction.

The procedure is summarized in the steps below:

''')

st.write('🔹 the fundamental parameters and photometric data are obtained for a sample of open clusters from Dias et al. 2021, with updated values based on Gaia eDR3 data;')
st.write('🔹 the fundamental parameters are used in the generation of synthetic clusters which will be compared to the observed one in a Monte Carlo procedure;')
st.write('🔹 the Monte Carlo procedure generates a sample of individual mass estimates for each observed cluster star;')
st.write('🔹 based on comparison to the synthetic clusters, stars are labeled as binary or not and a companion mass is estimated if appropriate;')
st.write('🔹 the final individual star masses (and companions when present) are obtained by averaging the sample of mass estimates generated by the Monte Carlo procedure;')
st.write('🔹 the final uncertainties are obtained by the standard deviation of the sample of mass estimates;')
st.write('🔹 after calculating individual star masses, we obtain the present-day mass function by fitting a function to the cluster stellar mass distribution obtained via a histogram of the mass estimates;')
st.write('🔹 the fitted present-day mass function is subsequently used to extrapolate the population of unseen low-mass stars, as well as the unseen mass in remnants of evolved stars')
st.write('🔹 the mass obtained for the observed stars (single and binary), the mass of unseen low mass stars, the mass of remnants of evolved stars and the contribution of unseen binaries are added to obtain the final mass of the cluster.')


st.write('''
In our procedure, the estimation of the mass of each member star observed in a given 
open cluster is the fundamental necessary step that needs to be carried out, 
before the cluster mass can be obtained. As mentioned previously, with the open 
cluster member stars defined, the Monte-Carlo method compares generated synthetic 
clusters to the observed ones to determine the masses of the individual member stars. 
To generate the synthetic cluster we need a given set of theoretical isochrones 
and in this work we use the Padova PARSEC version 1.2S set of isochrones described 
in detail in Bressan et al. (2012). The synthetic clusters are generated with a 
predefined number of stars with masses drawn from a probability distribution parameterized 
by the well-known Chabrier initial mass function Chabrier 2003. In this work, 
we adopted a number of generated stars of 10000. A fraction of binary stars of 50% 
is also adopted, with the binary system companion star masses drawn from a 
uniform distribution with values varying from 0 to the primary star mass. Photometric 
errors, as per the Gaia data definition Gaia Collaboration et al. 2016, are also included in the synthetic cluster.

For each star in the observed cluster, we compared its magnitudes to each of the 
10000 stars generated in the synthetic cluster, finding the one with the smallest difference 
in magnitude. This step effectively finds the synthetic star with the minimum Euclidean distance 
from the observed one in magnitude space, according to the following equation:


''')

st.latex(r'''
         d_i  = \min_{s\in S} ~ \sqrt {\sum _{j=1}^{m}  \left( O_{ij}-s_j\right)^2 }'''
         )

st.write('''
         where $d_i$ is the minimum distance of the star of the observed cluster $O$, 
         to the $s$ stars in the synthetic cluster $S$, measured in the $jth$ magnitude 
         band of the $m$ distinct bands available Gaia eDR3: G, GBP and GRP in this work.
         
         With the closest synthetic star determined, we check if it corresponds to a binary. 
         If it is, we mark the observed star as a binary and assign to it the corresponding 
         primary and secondary masses, since for the synthetic cluster those are known. Else,
         we assign the mass of the nearest synthetic cluster star to the observed star. The process 
         is repeated a large number of times, each time with a distinct synthetic cluster generated 
         by varying individual stars. The final mass of the observed stars and their companions 
         are adopted as the median of the respective sample of masses determined. The errors are 
         obtained by the standard deviation of the estimates in each case. We note here that, 
         since the method determines masses based on the minimization of Euclidean distances 
         in magnitude space, the distribution of binary system companion masses is adopted 
         for the synthetic cluster solely to efficiently sample the CMD region where binaries 
         are likely to be located. The actual distribution of mass fractions in binary systems 
         for a given observed cluster is determined a posteriori from the estimated stellar masses. 
         The procedure is illustrated in Fig. \ref{fig:sobreposicoes} where we have generated a 
         simulated open cluster with 50 member stars overlaid on a synthetic cluster generated 
         with the same referenced parameters with 10000 synthetic stars.

        To validate the stellar mass estimation method, a grid of synthetic clusters was generated 
        with log(age) varying from 6.6 to 9.5; reddening from 0.5 to 3.0 magnitudes; distances 
        from 1 to 5 kpc and with 300 observed stars, 50\% of which are binary systems. We then 
        compared the results of our mass estimation procedure to the input masses of the generated 
        grid. In Fig. \ref{fig:mass_error} we show an example of the validation for a simulated 
        cluster of log(age) = 8.5, distance = 1.0 kpc, and $A_v$ = 1.0 mag. We can see that 
        results are in good agreement with the input synthetic masses, with binary systems showing 
        larger differences as expected.


    The individual mass estimates also vary with respect to cluster ages and distances, 
    as shown in Fig. \ref{fig:indMass_error}. As expected, the relative errors are 
    worst for binaries and increase with age and distance, also with increasing spread. 
    The behaviour is expected as the photometric errors affect proportionally more 
    the clusters at higher distances. Young clusters also show larger uncertainties 
    due to their more undefined turn-off region in colour-magnitude space.
         
         ''')
         
st.subheader('We are updating this page...')

